### PR TITLE
Fix documentation: something -> thing

### PR DESCRIPTION
**Pull request by nick4eva**
This is to avoid confusion

### CODE REVIEW

**Comment by nick4eva** [comment]
Is it still worth to merge?

**Review by jsvd — COMMENTED** [review]
thanks for the contribution @nick4eva , can I bother you to do an extra thing? since documentation is generated on elastic.co based on new released versions, can you do a patch version bump to 4.0.7 in the .gemspec and add an entry to the CHANGELOG.md for this documentation fix like we did for 4.0.6 (i.e. https://github.com/logstash-plugins/logstash-filter-metrics/blob/master/CHANGELOG.md#406)? I'll take care of releasing this ASAP

**Comment by nick4eva** [comment]
@jsvd done.

**Comment by jsvd** [comment]
Thanks for your work @nick4eva , this has been merged as 402ffca.
This has been published https://rubygems.org/gems/logstash-filter-metrics/versions/4.0.7
Propagation to the elastic.co docs takes some time.

**Pull request closed without merging**
