### PR TITLE
Add support for add_field and add_tag options

### PR DESCRIPTION
**Pull request by IldarMinaev**
Simply remove processing of add_field and add_tag options from Base class to metrics filter, store events locally on Metrics filter and flush it.

### CODE REVIEW

**Comment by bwdezend** [comment]
Is there any movement on this issue? I am currently blocked in implementing a metrics filter due to this not working the way the documentation states.

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by purbon** [comment]
@bwdezend We do our best to keep track of everything, but that is hard for our small team. Are you open to help us validating this issue? can you provide some tests out of it? this would help us moving forward.

**Comment by bwdezend** [comment]
I'm able and willing to test.  What would be the best way for me to help?

**Comment by purbon** [comment]
@IldarMinaev thanks a lot for your contribution, I'm sorry it took a long time for us to come back here. to move this forward we would like to add some test that verify this capabilities. Are you open to do that? also this PR will need rebase with master, code is old this days.

**Comment by purbon** [comment]
@bwdezend thanks a lot, code this days is quite old (our fault not to come back before). Would be nice to work on getting this up to date with current core version. But for testing, would be great to verify if this works as expected, this could be done manually, or if you are comfortable with ruby, adding some specs to the project. Makes sense to you?

**Comment by purbon** [comment]
@IldarMinaev test are failing, can you verify that? 

@bwdezend I see current test failing for this PR, this might be a good start point to get this merged soon.

**Comment by bwdezend** [comment]
My ruby is passable. I'm happy to take a look and help where I can. I will pull the plugin manually and install on my testing host and make sure the changes have the desired effect.

**Comment by purbon** [comment]
awesome!!! this is very nice of you @bwdezend, as soon as we get this green we can merge it! I'm waiting to do the reviews! :+1:

**Comment by bwdezend** [comment]
Unfortunately, the code from IldarMinaev needs more work. Here is our filter stanza for testing:

```
filter {

  if [type] == "application" {
    metrics {
      meter          => "application_count" # Must be unique
      flush_interval => 15
      rates          => [1]
      add_field      => { "statsd_metric_name" => "application_count" }
      add_field      => { "statsd_metric_value" => "%{application_count.rate_1m}" }
    }
  }

  if exception {
    metrics {
      meter          => "%{exception}"
      flush_interval => 15
      rates          => [1]
      add_field      => { "statsd_metric_name"  => "%{exception}"}
      add_field      => { "statsd_metric_value" => "%{%{exception}.rate_1m}" }
    }
  }
}
```


Running 10 test log entries through the filter generates the following debug output:

```
{
                     "@version" => "1",
                   "@timestamp" => "2015-11-04T15:46:31.758Z",
                      "message" => "graph00",
      "application_count.count" => 10,
    "application_count.rate_1m" => 2.0,
          "statsd_metric_value" => "%{application_count.rate_1m}",
           "statsd_metric_name" => "application_count"
}
{
                                 "@version" => "1",
                               "@timestamp" => "2015-11-04T15:46:31.763Z",
                                  "message" => "graph00",
      "com.example.ReadOnlyException.count" => 10,
    "com.example.ReadOnlyException.rate_1m" => 2.0,
                      "statsd_metric_value" => "%{%{exception}.rate_1m}",
                       "statsd_metric_name" => "com.example.ReadOnlyException"
}
```


The current version of the plugin returns these entries:

```
{
                     "@version" => "1",
                   "@timestamp" => "2015-11-04T15:48:18.420Z",
                      "message" => "graph00",
      "application_count.count" => 10,
    "application_count.rate_1m" => 2.0,
           "statsd_metric_name" => "application_count",
          "statsd_metric_value" => "2.0"
}
{
                                 "@version" => "1",
                               "@timestamp" => "2015-11-04T15:48:18.426Z",
                                  "message" => "graph00",
      "com.example.ReadOnlyException.count" => 10,
    "com.example.ReadOnlyException.rate_1m" => 2.0,
                       "statsd_metric_name" => "%{exception}",
                      "statsd_metric_value" => "%{%{exception}.rate_1m}"
}
```

**Comment by purbon** [comment]
@bwdezend thanks for testing, if you want to take shot and help @IldarMinaev, it will also speed things up! I'm here to support you as much of possible.

**Comment by bwdezend** [comment]
@purbon I'll do my best. This isn't my highest priority deployment issue, so I can't spend quality time on coding it just now, but I'll work on this over the next few days. @IldarMinaev, if you have anything I can test on, I'm happy to do tests.

**Comment by bwdezend** [comment]
We have worked around this bug using the statsd plugin directly rather than feed metrics through the metrics plugin. It's far less efficient unfortunately, but it is working. This means my time to spend working on this bug is even further lower on the list. I will still attempt to get back to it soon.

**Comment by gauthier-delacroix** [comment]
This is quite a fat bug (given the feature is documented as dynamic and it's obviously static only)...anything changed since Nov 2015 ?

**Comment by rvrignaud** [comment]
Hi. I agree with @gauthier-delacroix . IMHO this is not an enhancement as documentation clearly specify that add_field and add_tag are dynamic. I think documentation should at least be fixed.

**Comment by dinarsalem** [comment]
is their any update on this bug?

**Comment by suraj-soni** [comment]
Bump ^. Do we have an update ETA on this ?

**Comment by suraj-soni** [comment]
Do we have an update on this ?

**Comment by karmi** [comment]
Hi @IldarMinaev, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-filter-metrics/pull/10.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by karmi** [comment]
Hi @IldarMinaev, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-filter-metrics/pull/10.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Pull request closed without merging**
