### PR TITLE
Split metrics

### PR DESCRIPTION
**Pull request by tebriel**
I am currently shipping data to datadog, and having the metrics broken up by what metric they're tracking when they're emitted is about 90% of my solution, so I've implemented it here.
Thanks!
Chris

### CODE REVIEW

**Comment by berglh** [comment]
@tebriel Does this address this following issue by splitting each metric into a separate document? 

- [Generate one event per metric name #30](https://github.com/logstash-plugins/logstash-filter-metrics/issues/30)

Would be great to get this going so that we can track counts of logs from multiple sources.

**Comment by tebriel** [comment]
Yeah, that seems like what I implemented before. I now have a ruby filter followed by a split filter. This would be way better.


On May 24, 2016, at 8:20 PM, Berg Lloyd-Haig <notifications@github.com<mailto:notifications@github.com>> wrote:


@tebriel<https://github.com/tebriel> Does this address this following issue by splitting each metric into a separate document?

  *   Generate one event per metric name #30<https://github.com/logstash-plugins/logstash-filter-metrics/issues/30>

Would be great to get this going so that we can track counts of logs from multiple sources.

-

**Comment by berglh** [comment]
Would be great to get this feature tested/merged so we can generate individual metric events per log source :+1:

**Comment by tebriel** [comment]
We don't use this any more, and I'm not in a position to resolve the merge conflicts and fix the PR, closing.

**Comment by berglh** [comment]
@tebriel I did fix up the diff and seemed to work for me after building:

https://github.com/berglh/logstash-filter-metrics/commit/7971a7d2cc744230496ab4b90e5ed9af6cd4bbd9

**Comment by tebriel** [comment]
@berglh good luck! I haven't touched a logstash plugin since this one in 2016, so I don't think I'd be much help but if I can help you please let me know.

**Pull request closed without merging**
